
class Prefijo {

  String pais;
  String numeroPref;
  String bandera;

  Prefijo({
    required this.pais,
    required this.numeroPref,
    required this.bandera,
  });

}



List<Prefijo> listaPrefijos(){
  return <Prefijo> [

Prefijo(pais: 'Afganistán'	,numeroPref: '+93', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Afganistan.svg"),
Prefijo(pais: 'Albania'	,numeroPref: '+355', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Albania.svg"),
Prefijo(pais: 'Alemania'	,numeroPref: '+49', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Alemania.svg"),
Prefijo(pais: 'Andorra'	,numeroPref: '+376', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Andorra.svg"),
Prefijo(pais: 'Angola'	,numeroPref: '+244', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Angola.svg"),
Prefijo(pais: 'Antigua y Barbuda'	, numeroPref: '+1', bandera: 	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Antigua-y-Barbuda.svg"),
Prefijo(pais: 'Arabia Saudita'	, numeroPref: '+966',	bandera: "https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Arabia-Saudi.svg"	),
Prefijo(pais: 'Argelia'	,numeroPref: '+213', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Argelia.svg"),
Prefijo(pais: 'Argentina'	,numeroPref: '+54', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Argentina.svg"),
Prefijo(pais: 'Armenia'	,numeroPref: '+374', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Armenia.svg"),
Prefijo(pais: 'Australia'	,numeroPref: '+61', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Australia.svg"),
Prefijo(pais: 'Austria'	,numeroPref: '+43', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Austria.svg"),
Prefijo(pais: 'Azerbaiyán'	,numeroPref: '+994', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Azerbaiyan.svg"),
Prefijo(pais: 'Bahamas'	,numeroPref: '+1', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Bahamas.svg"),
Prefijo(pais: 'Bangladés'	,numeroPref: '+880', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Banglades.svg"),
Prefijo(pais: 'Barbados'	,numeroPref: '+1', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Barbados.svg"),
Prefijo(pais: 'Baréin'	,numeroPref: '+973', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Barein.svg"),
Prefijo(pais: 'Bélgica'	,numeroPref: '+32', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Belgica.svg"),
Prefijo(pais: 'Belice'	,numeroPref: '+501', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Belice.svg"),
Prefijo(pais: 'Benin'	,numeroPref: '+229', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Benin.svg"),
Prefijo(pais: 'Bielorrusia'	,numeroPref: '+375', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Bielorrusia.svg"),
Prefijo(pais: 'Bolivia'	,numeroPref: '+591', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Bolivia.svg"),
Prefijo(pais: 'Bosnia y Herzegovina'	, numeroPref: '+387', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Bosnia-y-Herzegovina.svg")	,
Prefijo(pais: 'Botsuana'	,numeroPref: '+267', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Botsuana.svg"),
Prefijo(pais: 'Brasil'	,numeroPref: '+55', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Brasil.svg"),
Prefijo(pais: 'Brunéi'	,numeroPref: '+673', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Brunei.svg"),
Prefijo(pais: 'Bulgaria'	,numeroPref: '+359', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Bulgaria.svg"),
Prefijo(pais: 'Burkina Faso'	,numeroPref: '+226', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Burkina-Faso.svg")	,
Prefijo(pais: 'Burundi'	,numeroPref: '+257', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Burundi.svg"),
Prefijo(pais: 'Bután'	,numeroPref: '+975', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Butan.svg"),
Prefijo(pais: 'Cabo Verde'	,numeroPref: '+238', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Cabo-Verde.svg")	,
Prefijo(pais: 'Camboya'	,numeroPref: '+855', bandera:	"https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_Cambodia.svg"),
Prefijo(pais: 'Camerún'	,numeroPref: '+237', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Camerun.svg"),
Prefijo(pais: 'Canadá'	,numeroPref: '+1', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Canada.svg"),
Prefijo(pais: 'Catar'	,numeroPref: '+974', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Catar.svg"),
Prefijo(pais: 'Chad'	,numeroPref: '+235', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Chad.svg"),
Prefijo(pais: 'Chile'	,numeroPref: '+56', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Chile.svg"),
Prefijo(pais: 'China'	,numeroPref: '+86', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-China.svg"),
Prefijo(pais: 'Chipre'	,numeroPref: '+357', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Chipre.svg"),
Prefijo(pais: 'Colombia'	,numeroPref: '+57', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Colombia.svg"),
Prefijo(pais: 'Comoras'	,numeroPref: '+269', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Comoros.svg"),
Prefijo(pais: 'Corea del Norte'	, numeroPref: '+850', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Corea-del-Norte.svg")	,
Prefijo(pais: 'Corea del Sur'	, numeroPref: '+82', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Corea-del-Sur.svg")	,
Prefijo(pais: 'Costa de Marfil'	, numeroPref: '+225', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Costa-de-Marfil.svg"),
Prefijo(pais: 'Costa Rica'	,numeroPref: '+506', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Costa-Rica.svg")	,
Prefijo(pais: 'Croacia'	,numeroPref: '+385', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Croacia.svg"),
Prefijo(pais: 'Cuba'	,numeroPref: '+53', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Cuba.svg"),
Prefijo(pais: 'Dinamarca'	,numeroPref: '+45', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Dinamarca.svg"),
Prefijo(pais: 'Dominica'	,numeroPref: '+1', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Dominica.svg"),
Prefijo(pais: 'Ecuador'	,numeroPref: '+593', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Ecuador.svg"),
Prefijo(pais: 'Egipto'	,numeroPref: '+20', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Egipto.svg"),
Prefijo(pais: 'El Salvador'	,numeroPref: '+503', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-El-Salvador.svg")	,
Prefijo(pais: 'Emiratos Árabes Unidos'	, numeroPref: '+971', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Emiratos-Arabes-Unidos.svg")	,
Prefijo(pais: 'Eritrea'	,numeroPref: '+291', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Eritrea.svg"),
Prefijo(pais: 'Eslovaquia'	,numeroPref: '+421', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Eslovaquia.svg"),
Prefijo(pais: 'Eslovenia'	,numeroPref: '+386', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Eslovenia.svg"),
Prefijo(pais: 'España'	,numeroPref: '+34', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Espan%CC%83a.svg"),
Prefijo(pais: 'Estados Unidos'	,numeroPref: '+1', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Estados-Unidos.svg")	,
Prefijo(pais: 'Estonia'	,numeroPref: '+372', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Estonia.svg"),
Prefijo(pais: 'Etiopía'	,numeroPref: '+251', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Etiopia.svg"),
Prefijo(pais: 'Fiji'	,numeroPref: '+679', bandera:	"https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Fiji.svg"),
Prefijo(pais: 'Filipinas'	,numeroPref: '+63', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Filipinas.svg"),
Prefijo(pais: 'Finlandia'	,numeroPref: '+358', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Finlandia.svg"),
Prefijo(pais: 'Francia'	,numeroPref: '+33', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Francia.svg"),
Prefijo(pais: 'Gabón'	,numeroPref: '+241', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Gabon.svg"),
Prefijo(pais: 'Gambia'	,numeroPref: '+220', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Gambia.svg"),
Prefijo(pais: 'Georgia'	,numeroPref: '+995', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Georgia.svg"),
Prefijo(pais: 'Ghana'	,numeroPref: '+233', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Ghana.svg"),
Prefijo(pais: 'Granada'	,numeroPref: '+1', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Granada.svg"),
Prefijo(pais: 'Grecia'	,numeroPref: '+30', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Grecia.svg"),
Prefijo(pais: 'Guatemala'	,numeroPref: '+502', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Guatemala.svg"),
Prefijo(pais: 'Guinea'	,numeroPref: '+224', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Guinea.svg"),
Prefijo(pais: 'Guinea Ecuatorial'	,numeroPref: '+240', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Guinea-Ecuatorial.svg")	,
Prefijo(pais: 'Guinea-Bisáu'	,numeroPref: '+245',	bandera: "https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Guinea-Bissau.svg"	),
Prefijo(pais: 'Guyana'	,numeroPref: '+592', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Guyana.svg"),
Prefijo(pais: 'Haití'	,numeroPref: '+509', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Haiti.svg"),
Prefijo(pais: 'Honduras'	,numeroPref: '+504', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Honduras.svg"),
Prefijo(pais: 'Hungría'	,numeroPref: '+36', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Hungria.svg"),
Prefijo(pais: 'India'	,numeroPref: '+91', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-India.svg"),
Prefijo(pais: 'Indonesia'	,numeroPref: '+62', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Indonesia.svg"),
Prefijo(pais: 'Irak'	,numeroPref: '+964', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Irak.svg"),
Prefijo(pais: 'Irán'	,numeroPref: '+98', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Iran.svg"),
Prefijo(pais: 'Irlanda'	,numeroPref: '+353', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Irlanda.svg"),
Prefijo(pais: 'Islandia'	,numeroPref: '+354', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Islandia.svg"),
Prefijo(pais: 'Islas Marshall'	,numeroPref: '+692', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Islas-Marshall.svg")	,
Prefijo(pais: 'Islas Salomón'	,numeroPref: '+677', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Islas-Salomon.svg")	,
Prefijo(pais: 'Israel'	,numeroPref: '+972', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Israel.svg"),
Prefijo(pais: 'Italia'	,numeroPref: '+39', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Italia.svg"),
Prefijo(pais: 'Jamaica'	,numeroPref: '+1', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Jamaica.svg"),
Prefijo(pais: 'Japón'	,numeroPref: '+81', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Japon.svg"),
Prefijo(pais: 'Jordania'	,numeroPref: '+962', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Jordania.svg"),
Prefijo(pais: 'Kazajistán'	,numeroPref: '+7', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Kazajistan.svg"),
Prefijo(pais: 'Kenia'	,numeroPref: '+254', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Kenia.svg"),
Prefijo(pais: 'Kirguistán'	,numeroPref: '+996', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Kirguistan.svg"),
Prefijo(pais: 'Kiribati'	,numeroPref: '+686', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Kiribati.svg"),
Prefijo(pais: 'Kuwait'	,numeroPref: '+965', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Kuwait.svg"),
Prefijo(pais: 'Laos'	,numeroPref: '+856', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Laos.svg"),
Prefijo(pais: 'Lesoto'	,numeroPref: '+266', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Lesotho.svg"),
Prefijo(pais: 'Letonia'	,numeroPref: '+371', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Letonia.svg"),
Prefijo(pais: 'Líbano'	,numeroPref: '+961', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Libano.svg"),
Prefijo(pais: 'Liberia'	,numeroPref: '+231', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Liberia.svg"),
Prefijo(pais: 'Libia'	,numeroPref: '+218', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Libia.svg"),
Prefijo(pais: 'Liechtenstein'	,numeroPref: '+423', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Liechtenstein.svg"),
Prefijo(pais: 'Lituania'	,numeroPref: '+370', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Lituania.svg"),
Prefijo(pais: 'Luxemburgo'	,numeroPref: '+352', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Luxemburgo.svg"),
Prefijo(pais: 'Macedonia'	,numeroPref: '+389', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Macedonia.svg"),
Prefijo(pais: 'Madagascar'	,numeroPref: '+261', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Madagascar.svg"),
Prefijo(pais: 'Malasia'	,numeroPref: '+60', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Malasia.svg"),
Prefijo(pais: 'Malaui'	,numeroPref: '+265', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Malawi.svg"),
Prefijo(pais: 'Maldivas'	,numeroPref: '+960', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Maldivas.svg"),
Prefijo(pais: 'Malí'	,numeroPref: '+223', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Mali.svg"),
Prefijo(pais: 'Malta'	,numeroPref: '+356', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Malta.svg"),
Prefijo(pais: 'Marruecos'	,numeroPref: '+212', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Marruecos.svg"),
Prefijo(pais: 'Mauricio'	,numeroPref: '+230', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Mauricio.svg"),
Prefijo(pais: 'Mauritania'	,numeroPref: '+222', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Mauritania.svg"),
Prefijo(pais: 'México'	,numeroPref: '+52', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Mexico.svg"),
Prefijo(pais: 'Micronesia'	,numeroPref: '+691', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Micronesia.svg"),
Prefijo(pais: 'Moldavia'	,numeroPref: '+373', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Moldavia.svg"),
Prefijo(pais: 'Mónaco'	,numeroPref: '+377', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Monaco.svg"),
Prefijo(pais: 'Mongolia'	,numeroPref: '+976', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Mongolia.svg"),
Prefijo(pais: 'Montenegro'	,numeroPref: '+382', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Montenegro.svg"),
Prefijo(pais: 'Mozambique'	,numeroPref: '+258', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Mozambique.svg"),
Prefijo(pais: 'Myanmar'	,numeroPref: '+95', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Myanmar.svg"),
Prefijo(pais: 'Namibia'	,numeroPref: '+264', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Namibia.svg"),
Prefijo(pais: 'Nauru'	,numeroPref: '+674', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Nauru.svg"),
Prefijo(pais: 'Nepal'	,numeroPref: '+977', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Nepal.svg"),
Prefijo(pais: 'Nicaragua'	,numeroPref: '+505', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Nicaragua.svg"),
Prefijo(pais: 'Niger'	,numeroPref: '+227', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Niger.svg"),
Prefijo(pais: 'Nigeria'	,numeroPref: '+234', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Nigeria.svg"),
Prefijo(pais: 'Noruega'	,numeroPref: '+47', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Noruega.svg"),
Prefijo(pais: 'Nueva Zelanda'	,numeroPref: '+64', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Nueva-Zelanda.svg")	,
Prefijo(pais: 'Omán'	,numeroPref: '+968', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Oman.svg"),
Prefijo(pais: 'Países Bajos'	,numeroPref: '+31', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Paises-Bajos.svg")	,
Prefijo(pais: 'Pakistán'	,numeroPref: '+92', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Pakistan.svg"),
Prefijo(pais: 'Palaos'	,numeroPref: '+680', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Palaos.svg"),
Prefijo(pais: 'Panamá'	,numeroPref: '+507', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-panama.svg"),
Prefijo(pais: 'Papúa Nueva Guinea'	, numeroPref: '+675', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Papua-Nueva-Guinea.svg")	,
Prefijo(pais: 'Paraguay'	,numeroPref: '+595', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Paraguay.svg"),
Prefijo(pais: 'Perú'	,numeroPref: '+51', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Peru.svg"),
Prefijo(pais: 'Polonia'	,numeroPref: '+48', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Polonia.svg"),
Prefijo(pais: 'Portugal'	,numeroPref: '+351', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Portugal.svg"),
Prefijo(pais: 'Reino Unido'	,numeroPref: '+44', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Reino-Unido.svg")	,
Prefijo(pais: 'República Centroafricana'	,numeroPref: '+236', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Republica-Centroafricana.svg")	,
Prefijo(pais: 'República Checa'	,numeroPref: '+420', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Republica-Checa.svg")	,
Prefijo(pais: 'República del Congo'	, numeroPref: '+242', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Congo.svg")	,
Prefijo(pais: 'República Democratica del Congo'	, numeroPref: '+243', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Republica-Democratica-de-Congo.svg"),
Prefijo(pais: 'República Dominicana'	,numeroPref: '+1', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Republica-Dominicana.svg")	,
Prefijo(pais: 'Ruanda'	,numeroPref: '+250', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Ruanda.svg"),
Prefijo(pais: 'Rumania'	,numeroPref: '+40', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Rumania.svg"),
Prefijo(pais: 'Rusia'	,numeroPref: '+7', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Rusia.svg"),
Prefijo(pais: 'Samoa'	,numeroPref: '+685', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Samoa.svg"),
Prefijo(pais: 'San Cristóbal y Nieves'	, numeroPref: '+1',	bandera: "https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-San-Cristobal-y-Nieves.svg"	),
Prefijo(pais: 'San Marino'	,numeroPref: '+378', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-San-Marino.svg")	,
Prefijo(pais: 'San Vicente y las Granadinas', numeroPref: '+1', bandera: "https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-San-Vicenete-y-las-Granadinas.svg"),
Prefijo(pais: 'Santa Lucía'	,numeroPref: '+1', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Santa-Lucia.svg"),
Prefijo(pais: 'Santo Tomé y Príncipe', numeroPref: '+239', bandera:  "https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Santo-Tome-y-Principe.svg"),
Prefijo(pais: 'Senegal'	,numeroPref: '+221', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Senegal.svg"),
Prefijo(pais: 'Serbia'	,numeroPref: '+381', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Serbia.svg"),
Prefijo(pais: 'Seychelles'	,numeroPref: '+248', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Seychelles.svg"),
Prefijo(pais: 'Sierra Leona'	,numeroPref: '+232', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Sierra-Leona.svg")	,
Prefijo(pais: 'Singapur'	,numeroPref: '+65', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/bandera-de-singapur.svg"),
Prefijo(pais: 'Siria'	,numeroPref: '+963', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Siria.svg"),
Prefijo(pais: 'Somalia'	,numeroPref: '+252', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Somalia.svg"),
Prefijo(pais: 'Sri Lanka'	,numeroPref: '+94', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Sri-Lanka.svg")	,
Prefijo(pais: 'Suazilandia'	,numeroPref: '+268', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Suazilandia.svg"),
Prefijo(pais: 'Sudáfrica'	,numeroPref: '+27', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Sudafrica.svg"),
Prefijo(pais: 'Sudán'	,numeroPref: '+249', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Sudan.svg"),
Prefijo(pais: 'Sudán del Sur'	, numeroPref: '+211', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Sudan-del-Sur.svg")	,
Prefijo(pais: 'Suecia'	,numeroPref: '+46', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Suecia.svg"),
Prefijo(pais: 'Suiza'	,numeroPref: '+41', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Suiza.svg"),
Prefijo(pais: 'Surinam'	,numeroPref: '+597', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Surinam.svg"),
Prefijo(pais: 'Tailandia'	,numeroPref: '+66', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Tailandia.svg"),
Prefijo(pais: 'Tanzania'	,numeroPref: '+255', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Tanzania.svg"),
Prefijo(pais: 'Tayikistán'	,numeroPref: '+992', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Tayikistan.svg"),
Prefijo(pais: 'Timor Oriental'	,numeroPref: '+670', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Timor-Leste.svg")	,
Prefijo(pais: 'Togo'	,numeroPref: '+228', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Togo.svg"),
Prefijo(pais: 'Tonga'	,numeroPref: '+676', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Tonga.svg"),
Prefijo(pais: 'Trinidad y Tobago'	, numeroPref: '+1', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Trinidad-y-Tobago.svg")	,
Prefijo(pais: 'Túnez'	,numeroPref: '+216', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Tunez.svg"),
Prefijo(pais: 'Turkmenistán'	,numeroPref: '+993', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Turkmenistan.svg"),
Prefijo(pais: 'Turquía'	,numeroPref: '+90', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Turquia.svg"),
Prefijo(pais: 'Tuvalu'	,numeroPref: '+688', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Tuvalu.svg"),
Prefijo(pais: 'Ucrania'	,numeroPref: '+380', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Ucrania.svg"),
Prefijo(pais: 'Uganda'	,numeroPref: '+256', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Uganda.svg"),
Prefijo(pais: 'Uruguay'	,numeroPref: '+598', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Uruguay.svg"),
Prefijo(pais: 'Uzbekistán'	,numeroPref: '+998', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Uzbekistan.svg"),
Prefijo(pais: 'Vanuatu'	,numeroPref: '+678', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Vanuatu.svg"),
Prefijo(pais: 'Venezuela'	,numeroPref: '+58', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Venezuela.svg"),
Prefijo(pais: 'Vietnam'	,numeroPref: '+84', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Vietnam.svg"),
Prefijo(pais: 'Yemen'	,numeroPref: '+967', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Yemen.svg"),
Prefijo(pais: 'Yibuty'	,numeroPref: '+253', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Yibuti.svg"),
Prefijo(pais: 'Zambia'	,numeroPref: '+260', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Zambia.svg"),
Prefijo(pais: 'Zimbabue'	,numeroPref: '+263', bandera:	"https://proyectoviajero.com/wp-content/uploads/2021/03/Bandera-de-Zimbabue.svg"),













  
  ];
}